print("Hello World!\nHello World!\nHello World!")
print("Vivek"+"Ranjan")
print("Vivek"+" "+"Ranjan")
print("Day 1 - String Manipulation")
print("String Concatenation is done with the "+'"+"'+" sign")
print('e.g. print("Hello " + "world")')
print("New lines can be added with a backslash and n.")
